### ISSUE TITLE
Font Customization for Placeholder Label

### ISSUE THREAD

**Issue by cliftonlabrum** [FahimF/FloatLabelFields#3]
I can set the font on the `UITextField` I'm using, but how do I specify the font for the label above the text field?

![image](https://cloud.githubusercontent.com/assets/2513753/6990341/12bfee8c-da1f-11e4-86f6-837db7226416.png)

**Comment by FahimF** [comment]
The "titleFont" property should allow you to set the title font - however, there are two caveats:
1. The font you set will be used only in non-placeholder mode. In place-holder mode, the control will use the standard font since the control is using the built-in placeholder display functionality.

2. The title does not adjust for the font size changes currently. This is a bug that I'm in the process of fixing right now.
